#!/usr/bin/env python3
"""
Data pipeline: clone permissively-licensed embedded C repos, filter, dedup,
pack into a HuggingFace dataset for causal-LM fine-tuning.

Usage:
    python data/prepare_data.py --out data/processed/embedded_c_dataset
"""
import argparse
import hashlib
import os
import re
import subprocess
from pathlib import Path

from datasets import Dataset

# Permissive-license embedded / RTOS / control-systems corpora
REPOS = [
    ("https://github.com/FreeRTOS/FreeRTOS-Kernel.git", "MIT"),
    ("https://github.com/zephyrproject-rtos/zephyr.git", "Apache-2.0"),
    ("https://github.com/ARM-software/CMSIS_5.git", "Apache-2.0"),
    ("https://github.com/libopencm3/libopencm3.git", "LGPL-3.0"),
    ("https://github.com/eclipse-threadx/threadx.git", "MIT"),
    ("https://github.com/pms67/PID.git", "MIT"),
]

C_EXT = {".c", ".h"}
MIN_LINES, MAX_LINES = 10, 2000
MAX_LINE_LEN = 400  # skip minified/generated files


def clone(url: str, dst: Path) -> None:
    if dst.exists():
        return
    subprocess.run(
        ["git", "clone", "--depth", "1", url, str(dst)],
        check=True, capture_output=True,
    )


def is_valid(text: str) -> bool:
    lines = text.splitlines()
    if not (MIN_LINES <= len(lines) <= MAX_LINES):
        return False
    if any(len(l) > MAX_LINE_LEN for l in lines):
        return False
    # skip auto-generated files
    head = "\n".join(lines[:5]).lower()
    if "auto-generated" in head or "autogenerated" in head:
        return False
    return True


def collect(root: Path):
    seen_hashes = set()
    for p in root.rglob("*"):
        if p.suffix not in C_EXT or not p.is_file():
            continue
        try:
            text = p.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if not is_valid(text):
            continue
        h = hashlib.sha256(re.sub(r"\s+", "", text).encode()).hexdigest()
        if h in seen_hashes:  # exact-content dedup (whitespace-insensitive)
            continue
        seen_hashes.add(h)
        yield {"text": text, "path": str(p.relative_to(root)), "repo": root.name}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/processed/embedded_c_dataset")
    ap.add_argument("--workdir", default="data/raw")
    args = ap.parse_args()

    workdir = Path(args.workdir)
    workdir.mkdir(parents=True, exist_ok=True)

    records = []
    for url, license_ in REPOS:
        name = url.rstrip("/").split("/")[-1].removesuffix(".git")
        dst = workdir / name
        print(f"[clone] {name}")
        clone(url, dst)
        n_before = len(records)
        for rec in collect(dst):
            rec["license"] = license_
            records.append(rec)
        print(f"  -> {len(records) - n_before} files")

    ds = Dataset.from_list(records)
    ds = ds.train_test_split(test_size=0.02, seed=42)
    ds.save_to_disk(args.out)
    total_mb = sum(len(r["text"]) for r in records) / 1e6
    print(f"[done] {len(records)} files, {total_mb:.1f} MB -> {args.out}")


if __name__ == "__main__":
    main()
